workflows:
  android-release:
    name: Build e Deploy Android
    max_build_duration: 45
    environment:
      flutter: stable
      vars:
        PACKAGE_NAME: "com.example.imcapp"
      android_signing:
        keystore_reference: keystore_credentials
      groups:
        - google_play
    scripts:
      - name: Instalar dependências
        script: |
          flutter pub get

      - name: Gerar APK de release
        script: |
          flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk

    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
